repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        exclude: ^tests/utils/
      - id: no-commit-to-branch
        stages: [pre-commit]
      - id: trailing-whitespace

  - repo: https://github.com/fpgmaas/deptry
    rev: "0.12.0"
    hooks:
      - id: deptry
        name: deptry
        description: deptry is a command line tool to check for issues with dependencies in a Python project, such as unused or missing dependencies.
        entry: deptry .
        language: system
        always_run: true
        pass_filenames: false
