name: ci

on:
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]

jobs:
  quality-checks:
    uses: ./.github/workflows/quality-checks.yaml

  test:
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
