name: unit-and-doc-tests

on:
  workflow_call:
    inputs:
      cov-fail-under:
        type: number
        default: 80
        description: 'Percentage under which code coverage should fail the pipeline'
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: '3.12'

      - name: Run tests
        run: poetry run pytest tests/unit/ finding_the_mole --doctest-modules --cov=finding_the_mole --cov-fail-under=${{ inputs.cov-fail-under }} --cov-report=xml --cov-report=term-missing

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
